# Generated by Django 4.2.1 on 2024-01-07 13:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('corecode', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentBulkUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_uploaded', models.DateTimeField(auto_now=True)),
                ('csv_file', models.FileField(upload_to='students/bulkupload/')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10, verbose_name='Statut Courant')),
                ('registration_number', models.CharField(max_length=200, unique=True, verbose_name="Numero d'enregistrement")),
                ('name', models.CharField(default='', max_length=200, verbose_name='Nom')),
                ('firstname', models.CharField(max_length=200, verbose_name='Prenom')),
                ('arabic_name', models.CharField(default='', max_length=200, verbose_name='Nom complet en Arabe')),
                ('gender', models.CharField(choices=[('male', 'Garcon'), ('female', 'Fille')], default='male', max_length=10, verbose_name='Genre')),
                ('nationality', models.CharField(default='', max_length=20, verbose_name='Nationnalite')),
                ('date_of_birth', models.DateField(default=django.utils.timezone.now, verbose_name='Date de Naissance')),
                ('birth_city', models.CharField(choices=[('niamey', 'Niamey'), ('agadez', 'Agadez'), ('diffa', 'Diffa'), ('dosso', 'Dosso'), ('maradi', 'Maradi'), ('tahoua', 'Tahoua'), ('tillaberi', 'Tillaberi'), ('zinder', 'Zinder')], default='Niamey', max_length=10, verbose_name='Niamey')),
                ('date_of_admission', models.DateField(default=django.utils.timezone.now, verbose_name="Date d'admission")),
                ('parent_mobile_number', models.CharField(blank=True, max_length=13, validators=[django.core.validators.RegexValidator(message="Entered mobile number isn't in a right format!", regex='^[0-9]{10,15}$')], verbose_name='Contact parent')),
                ('address', models.TextField(blank=True)),
                ('has_learned_quran', models.CharField(blank=True, choices=[('yes', 'Oui'), ('no', 'Non')], default='yes', max_length=20, verbose_name="J'aide deja appris le Coran ")),
                ('health_state', models.CharField(choices=[('healthy', 'Sain'), ('unhealthy', 'Malade')], default='healthy', max_length=20, verbose_name='Etat de Sante')),
                ('passport', models.ImageField(blank=True, upload_to='students/passports/', verbose_name="Carte d'identite")),
                ('others', models.TextField(blank=True, verbose_name='Plus de details')),
                ('current_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='corecode.studentclass', verbose_name='Classe actuelle')),
            ],
            options={
                'ordering': ['name', 'firstname'],
            },
        ),
    ]
