# Generated by Django 4.2.1 on 2024-01-20 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='health_type',
            field=models.CharField(default='Aucun', max_length=100, verbose_name='Type de Maladie'),
        ),
    ]
