# Generated by Django 3.2.18 on 2023-11-23 20:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('corecode', '0004_auto_20201124_0614'),
        ('students', '0002_auto_20201124_0614'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['name', 'firstname']},
        ),
        migrations.RemoveField(
            model_name='student',
            name='other_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='surname',
        ),
        migrations.AddField(
            model_name='student',
            name='birth_city',
            field=models.CharField(choices=[('niamey', 'Niamey'), ('agadez', 'Agadez'), ('diffa', 'Diffa'), ('dosso', 'Dosso'), ('maradi', 'Maradi'), ('tahoua', 'Tahoua'), ('tillaberi', 'Tillaberi'), ('zinder', 'Zinder')], default='Niamey', max_length=10, verbose_name='Niamey'),
        ),
        migrations.AddField(
            model_name='student',
            name='has_learned_quran',
            field=models.CharField(choices=[(True, 'Oui'), (False, 'Non')], default=False, max_length=20, verbose_name="J'aide deja appris le Coran "),
        ),
        migrations.AddField(
            model_name='student',
            name='health_state',
            field=models.CharField(choices=[('healthy', 'Sain'), ('unhealthy', 'Malade')], default='healthy', max_length=20, verbose_name='Etat de Sante'),
        ),
        migrations.AddField(
            model_name='student',
            name='name',
            field=models.CharField(default='', max_length=200, verbose_name='Nom'),
        ),
        migrations.AddField(
            model_name='student',
            name='nationality',
            field=models.CharField(default='', max_length=20, verbose_name='Nationnalite'),
        ),
        migrations.AlterField(
            model_name='student',
            name='current_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='corecode.studentclass', verbose_name='Classe actuelle'),
        ),
        migrations.AlterField(
            model_name='student',
            name='current_status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10, verbose_name='Statut Courant'),
        ),
        migrations.AlterField(
            model_name='student',
            name='date_of_admission',
            field=models.DateField(default=django.utils.timezone.now, verbose_name="Date d'admission"),
        ),
        migrations.AlterField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date de Naissance'),
        ),
        migrations.AlterField(
            model_name='student',
            name='firstname',
            field=models.CharField(max_length=200, verbose_name='Prenom'),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('male', 'Garcon'), ('female', 'Fille')], default='male', max_length=10, verbose_name='Genre'),
        ),
        migrations.AlterField(
            model_name='student',
            name='others',
            field=models.TextField(blank=True, verbose_name='Plus de details'),
        ),
        migrations.AlterField(
            model_name='student',
            name='parent_mobile_number',
            field=models.CharField(blank=True, max_length=13, validators=[django.core.validators.RegexValidator(message="Entered mobile number isn't in a right format!", regex='^[0-9]{10,15}$')], verbose_name='Contact parent'),
        ),
        migrations.AlterField(
            model_name='student',
            name='passport',
            field=models.ImageField(blank=True, upload_to='students/passports/', verbose_name="Carte d'identite"),
        ),
        migrations.AlterField(
            model_name='student',
            name='registration_number',
            field=models.CharField(max_length=200, unique=True, verbose_name="Numero d'enregistrement"),
        ),
    ]
