# Generated by Django 4.2.1 on 2024-03-31 10:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_student_name_alter_student_registration_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='second_parent_mobile_number',
            field=models.CharField(blank=True, max_length=13, validators=[django.core.validators.RegexValidator(message="Entered mobile number isn't in a right format!", regex='^[0-9]{10,15}$')], verbose_name='Autre Contact parent'),
        ),
    ]
