# Generated by Django 4.2.3 on 2023-12-18 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_auto_20231123_2017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='has_learned_quran',
        ),
        migrations.RemoveField(
            model_name='student',
            name='health_state',
        ),
    ]
