# Generated by Django 4.2.1 on 2024-12-07 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_student_second_parent_mobile_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='section',
            field=models.CharField(choices=[('complexe', 'Complexe Coranique'), ('institut', 'Institut Coranique')], default='complexe', max_length=20, verbose_name='Section'),
        ),
    ]
