# Generated by Django 4.2 on 2024-01-03 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_remove_student_has_learned_quran_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='arabic_name',
            field=models.CharField(default='', max_length=200, verbose_name='Nom complet en Arabe'),
        ),
    ]
