# Generated by Django 4.2 on 2024-01-03 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_student_arabic_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='has_learned_quran',
            field=models.CharField(choices=[(True, 'Oui'), (False, 'Non')], default=False, max_length=20, verbose_name="J'aide deja appris le Coran "),
        ),
        migrations.AddField(
            model_name='student',
            name='health_state',
            field=models.CharField(choices=[('healthy', 'Sain'), ('unhealthy', 'Malade')], default='healthy', max_length=20, verbose_name='Etat de Sante'),
        ),
    ]
