# Generated by Django 4.2.1 on 2024-01-07 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corecode', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academicterm',
            name='arabic_name',
        ),
    ]
